[package]
name = "terminal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.7"
shellwords = "1.1.0"
lazy_static = "1.4.0"
ctrlc = "3.4.1"